# Generated by Django 2.1.2 on 2018-12-08 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='filename',
        ),
    ]
