CRAWLER_APP = {
    "DEFAULT_MAX_LINKS_COUNT": 1000,
    "DEFAULT_MAX_REQUESTS_TRIES": 2,
    "DEFAULT_TIME_BETWEEN_REQUEST_TRIES": 2,  # in seconds
    "DEFAULT_MIN_IMG_HEIGHT": 100,  # in px
    'DEFAULT_MIN_IMG_WIDTH': 100,
    "DEFAULT_MAX_IMG_SIZE": 1000,
}
