# Generated by Django 2.1.2 on 2018-12-06 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetsMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.IntegerField(default=1)),
                ('type', models.CharField(choices=[('0', 'MAIN'), ('1', 'SUB_TASK')], max_length=1)),
                ('parser', models.CharField(choices=[('0', 'GenericParser')], default=0, max_length=1)),
                ('crawler', models.CharField(choices=[('0', 'local'), ('1', 's3')], default=0, max_length=1)),
                ('target_url', models.URLField()),
                ('images_storage', models.CharField(default='0', max_length=1)),
                ('images_max_size', models.IntegerField(default=1000)),
                ('txt', models.TextField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('images', models.ManyToManyField(blank=True, to='media.Image')),
                ('sub_tasks', models.ManyToManyField(blank=True, to='crawler.Task')),
                ('targets_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crawler.TargetsMap')),
            ],
        ),
        migrations.CreateModel(
            name='VisitedTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField()),
                ('visited', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='targetsmap',
            name='visited_targets',
            field=models.ManyToManyField(to='crawler.VisitedTarget'),
        ),
    ]
