# Generated by Django 2.1.2 on 2018-12-07 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('crawler', '0003_auto_20181207_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(max_length=255)),
                ('error', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('images', models.ManyToManyField(to='media.Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='targetsmap',
            name='visited_targets',
        ),
        migrations.RemoveField(
            model_name='task',
            name='images',
        ),
        migrations.RemoveField(
            model_name='task',
            name='sub_tasks',
        ),
        migrations.RemoveField(
            model_name='task',
            name='targets_map',
        ),
        migrations.RemoveField(
            model_name='task',
            name='txt',
        ),
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.DeleteModel(
            name='TargetsMap',
        ),
        migrations.DeleteModel(
            name='VisitedTarget',
        ),
        migrations.AddField(
            model_name='node',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='crawler.Task'),
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('task', 'target_url')},
        ),
    ]
