# Generated by Django 2.1.2 on 2018-12-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_auto_20181207_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
