# Generated by Django 2.1.2 on 2018-12-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_node_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='images',
            field=models.ManyToManyField(blank=True, to='media.Image'),
        ),
    ]
