# Generated by Django 2.1.2 on 2018-12-09 15:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20181208_2352'),
        ('crawler', '0008_auto_20181207_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('target_url', models.URLField(max_length=255)),
                ('error', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('done', models.BooleanField(default=False)),
                ('images', models.ManyToManyField(blank=True, to='media.Image')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='crawler.Task')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='node',
            name='images',
        ),
        migrations.RemoveField(
            model_name='node',
            name='task',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('task', 'target_url')},
        ),
    ]
