# Generated by Django 2.1.2 on 2018-12-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0009_auto_20181209_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('0', 'text'), ('1', 'images'), ('3', 'text and images')], default=3, max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='images_storage',
            field=models.CharField(choices=[('0', 'local'), ('1', 's3')], default=0, max_length=1),
        ),
    ]
