# Generated by Django 2.1.2 on 2018-12-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0010_auto_20181210_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('0', 'text'), ('1', 'images'), ('2', 'text and images')], default=3, max_length=1),
        ),
    ]
